version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      server-minor-patch:
        update-types: [minor, patch]
      server-dev-tooling:
        dependency-type: development
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    groups:
      client-minor-patch:
        update-types: [minor, patch]
      client-dev-tooling:
        dependency-type: development
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
